### ISSUE TITLE
Why color: lighten($bg-color, $sat-ratio + 25);

### ISSUE THREAD

**Issue by corysimmons** [simurai/roots#1]
Why `$sat-ratio + 25`?

Btw, love this. Especially the color stuff.

**Comment by simurai** [comment]
You mean why `25` and not another number? Probably form here: https://github.com/simurai/roots/blob/master/app/css/_config.scss#L43

Can't really remember.. lol.. but I guess it's more or less a random number without much meaning.. just to test. Would be neat to somehow use a contrast tester like: http://jxnblk.com/colorable/demos/text/
