### ISSUE TITLE
Why boilerplate instead of lib again?

### ISSUE THREAD

**Issue by corysimmons** [simurai/roots#3]
I forget where we were with this conversation, but it just doesn't make sense to me why this repo has an `index.html` in it (or anything other than SCSS for that matter).

**Comment by simurai** [comment]
Well, this repo isn't actually meant to be a lib. More like a guideline. But I haven't written it yet.. first I need to finish the blog post. And all the files are just carried over from Oak and then tweaked a bit to test. 

Doesn't mean it can't be turned into a lib, but first I think the "fundamentals" need to be worked out.

**Comment by corysimmons** [comment]
Sure :+1:

**Comment by simurai** [comment]
@corysimmons I think if I ever do a lib, I actually need to use it for a "real-world" project. Like Primer gets used for GitHub. Twitter initially used Bootstrap, now I guess SUIT. Just doing it "blindly" makes it hard to know what's important  or if something works or doesn't.

Maybe it could be the lib used in tlk.io (that I work on as a side project). It's pretty specialized and doesn't have tons of controls, but at least I would use it for real.

**Comment by corysimmons** [comment]
I think my issue with it being a UI kit boilerplate is that it breaks the rule of modularity. You'd essentially be tying a UI kit to an HTML boilerplate. I think the best practice is to break apart projects into smaller modular projects so it just confuses me why this would have anything other than SCSS in the repo.

I totally agree on using stuff in the real world. If we can put some more work into :roots then I've always got client projects to test things out on.

Also, kudos on tlk.io - I've used it on ShopTalkShow Live. =)

**Comment by simurai** [comment]
>  it just confuses me why this would have anything other than SCSS in the repo.

That's just because I started :roots to test some stuff like it would be a real app and maybe later use it as a guideline and not meant to be used as drop-in lib. Yeah, for a lib, it would probably just be https://github.com/simurai/roots/tree/master/app/css and renamed to something else.

**Comment by corysimmons** [comment]
_whew_ Okay, that's what I was making sure of. =)

I thought you were doing your boilerplate thing again. XD
